### PR TITLE
Heroku deploy

### PR DESCRIPTION
**Pull request by ezeilo-su**

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required 🔴 

Hello,

Thank you for the well-done job so far
However, there are some missing requirements

1- There is no link to your deployed app in your README
Not possible to check your work

2- The `rubocop.yml` file of your project is different the required one. 
Kindly, follow this [link](https://github.com/microverseinc/linters-config/tree/master/ror) to set up the good one

Kindly, make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

Hello, Team 👋  Great job! 👏  
Both of you have done well on this project.

I see you made mention of having some issues while trying to deploy your app. I tried reaching out on slack to know the exact problem, kindly reach out to me as well or drop a screenshot of the error on the general slack channel.

But before that, since you have been deploying before now, I am assuming all credentials to Heroku are set on your local machine.

If you're pushing from develop branch, use this command
`git push heroku $BRANCH_NAME:master` in your case it should be `git push heroku develop:master`

[OPTIONAL] It will be nice to segment your readme file to have appropriate headings instead of merging all into **What we implemented**
I see **Build With** and **Getting Started or How to Setup Locally** section all in that one section.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by tirthajyoti-ghosh — APPROVED** [review]
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Comment by ezeilo-su** [comment]
Thanks to all the TSEs and friends who contributed to this project making it a success. I'm proud of you guys: @ebukaume, @descholar-ceo, @Spayco. May God bless you all!

**Pull request merged**
